### ISSUE TITLE
ask for question

### ISSUE THREAD

**Issue by carryTatum** [usc-isi-i2/isi-tkg-icl#1]
hello author , I am interested in your work ,when I run your code(run_rule.py file).I can not run your code ,the issue as follows:
![image](https://github.com/usc-isi-i2/isi-tkg-icl/assets/74437714/6eeed704-f50d-4175-a526-9b3aef8da9f3)
What should I do so that solve this problem , in your file I can not found these jsonl

**Comment by LiAi16** [comment]
you should add a folder "output" and that work for me
